pipeline {
    agent any
    stages {
        stage('Start') {
            steps {
                echo 'Starting Pipeline!'
            }
        }
        stage("Clean Up"){
            steps {
                deleteDir()
            }
        }
        stage("Clone Repo"){
            steps {
                sh "git clone https://github.com/jjdlux/simple-java-maven-app.git"
            }
        }
        stage('Build') {
            steps {
                dir('simple-java-maven-app') {
                    echo 'Building Package!'
                    sh 'mvn -B -Denforcer.skip=true -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir('simple-java-maven-app') {
                    echo 'Starting Tests!'
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'simple-java-maven-app/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                dir('simple-java-maven-app') {
                    echo 'Starting Deliver!'
                    sh './jenkins/scripts/deliver.sh'
                }
            }
        }
        stage('Complete') {
            steps {
                echo 'Completed sub branch!'
            }
        }
    }
}
